# ?????????? ? ???????
project.name=WebLab3
project.version=1.0-SNAPSHOT
project.group=org.example

# ???? ? ??????????
src.dir=src/main/kotlin
webapp.dir=src/main/webapp
resources.dir=src/main/resources

# ???? ??????
build.dir=build/ant
classes.dir=${build.dir}/classes
dist.dir=dist
lib.dir=lib
doc.dir=${build.dir}/javadoc

#  WAR
war.name=${project.name}-${project.version}.war

#  ??????????
java.version=17
kotlin.ant.jar=${lib.dir}/kotlin-ant.jar

#  SCP helios
scp.host=helios.cs.ifmo.ru
scp.user=s467550
scp.password=mndW-0608
scp.remote.dir=/home/studs/s467550/OPIWeb

#  diff
# ?????? ?????????? Git, SVN-???? ??????????? ??? ????????
diff.protected.classes=MainKt

#  env: ?????????????? ?????????
env.jvmargs.1=-Xmx256m -Xms64m
env.jvmargs.2=-Xmx512m -Xms128m -verbose:gc

# dokka (???????? ?????? ??? ??????? ???????????)
dokka.dir=dokka
dokka.cli.jar=${dokka.dir}/dokka-cli-1.9.20.jar
dokka.base.jar=${dokka.dir}/dokka-base-1.9.20.jar
dokka.analysis.jar=${dokka.dir}/analysis-kotlin-descriptors-1.9.20.jar
dokka.freemarker.jar=${dokka.dir}/freemarker-2.3.32.jar
dokka.html.jar=${dokka.dir}/kotlinx-html-jvm-0.11.0.jar

# SVN
svn.working.dir=C:\\svnLab3Opi\\working
svn.protected.classes=AreaCheckBean,ResultEntity

# ?????
test.src.dir=src/test/kotlin
test.classes.dir=${build.dir}/test-classes
junit.standalone.jar=${lib.dir}/junit-platform-console-standalone-1.10.0.jar